Thread tests
lsst-ts/ts_cRIOcpp pull request #24
Opened 2021-11-24 09:29 UTC by pkubanek

See tests. They don't show any race in ending thread.

2021-11-24 09:33 UTC, pkubanek commented
My fault, I need to start thread to see the race.

2021-11-24 18:36 UTC, jgates108 reviewed
The changes you made should work as is, but the existing code probably expects a join to happen in the destructor.

2021-11-24 18:36 UTC, jgates108 commented on src/LSST/cRIO/Thread.cpp
>          delete _thread;
The delete should probably occur in the destructor and use an atomic flag for join being called. 
private:
   std::atomic<bool> _joinCalled{false};

if (_joinCalled.exchange(true) == false)  {
     _thread->join();
} else {
    throw Bug("join called multiple times");
}


Thread::~Thread() {
     if (_joinCalled.exchange(true) == false) {
          logerror("join not called before destructor");
          _thread->join();
    }
    delete _thread;
}

2021-11-25 15:31 UTC, pkubanek commented on src/LSST/cRIO/Thread.cpp
>          delete _thread;
I decided to drop join the call - it's not called in descendants nor from outside (except for tests calls), so doesn't make any sense for us.

2021-11-30 19:53 UTC, jgates108 requested changes
The condition_variables need specific things to check and the wait calls need to check them.

2021-11-30 19:53 UTC, jgates108 commented on src/LSST/cRIO/Thread.cpp
> +        _startCondition.wait(lg);
There needs to be a variable associated with _startCondition. The OS will occasionally wake up `wait()` for no reason, so there needs to be a variable to check.

The mutex associated with the condition_variable needs to be consistent, always using runMutex is probably fine.
in the class definition, _threadStarted needs to be defined with an initial value of false.
This should be `_startCondition.wait(lg, [this](){ return _threadStarted; });` and before `notify()` is called, `_threadStarted` should be set to true.

2021-11-30 19:53 UTC, jgates108 commented on src/LSST/cRIO/Thread.cpp
> +    _startCondition.notify_one();
Add `_threadStarted = true;` before this line.

2021-11-30 19:53 UTC, jgates108 commented on tests/test_Application.cpp
> +            runCondition.wait(lock);
There needs to be something to check with `runCondition.wait(lock);`

2021-11-30 19:53 UTC, jgates108 commented on tests/test_Thread.cpp
> +            runCondition.wait(lock);
Again, runCondition needs to check a variable as the OS will wake them up randomly.

2021-11-30 19:53 UTC, jgates108 commented on include/cRIO/Thread.h
>      std::condition_variable runCondition;
Having runCondition defined here, without a specific condition assoicated with it, is asking for trouble. It's essential that condition variables are associated with something specific that can be checked. The OS will wake up wait() calls randomly, and without  that condition to check, this can result in devestating problems that happen very infrequently (like once every three months while running continuously). wait() calls should just about always have a lambda function defined to make the check.

2021-12-01 08:38 UTC, pkubanek commented on tests/test_Thread.cpp
> +            runCondition.wait(lock);
The only purpose of this loop is to run until keepRunning is turned false. This is the variable associated with runCondition in test classes. If runCondition wakes up, keepRunning will keep the loop running until stop is called, which turns keepRunning false and notifies condition.

2021-12-01 08:38 UTC, pkubanek commented on tests/test_Application.cpp
> +            runCondition.wait(lock);
See below, keepRunning is the variable.

2021-12-01 08:39 UTC, pkubanek commented on include/cRIO/Thread.h
>      std::condition_variable runCondition;
created and used _threadRunning as suggested

2021-12-01 08:39 UTC, pkubanek commented on src/LSST/cRIO/Thread.cpp
> +    _startCondition.notify_one();
Added

2021-12-01 08:40 UTC, pkubanek commented on src/LSST/cRIO/Thread.cpp
> +        _startCondition.wait(lg);
Changed to wait_until, added variable as suggested.

2021-12-01 17:50 UTC, pkubanek commented on src/LSST/cRIO/Thread.cpp
>      }
Race and join problem were solved by signaling thread end with _threadStarted = false and conditional variable associated with it.

2021-12-01 19:14 UTC, jgates108 commented on tests/test_Thread.cpp
> +            } catch (std::runtime_error&) {
I think throwing "Thread: Cannot stop thread!" is a failure now. It probably shouldn't be caught.

2021-12-01 19:18 UTC, pkubanek commented on tests/test_Thread.cpp
> +            } catch (std::runtime_error&) {
StopThread is designed to try to fire multiple stop methods to prove it is thread-safe. Multiple StopThreads are created and run at the same time, to see they work as expected. Only one can actually succeed in stopping the thread. Others shall fail.

2021-12-01 19:26 UTC, jgates108 commented on src/LSST/cRIO/Thread.cpp
> +Thread::Thread() : keepRunning(false), _threadStarted(false) { _thread = NULL; }
For most variables, and especially for variables like keepRunning (there's pretty much no reason the initial value should not be false), I like putting the initialization in the header file `bool keepRunning = false;`. This has an advantage in that when another constructor is created, you don't have to duplicate the initialization. With long running projects and maintenance, duplicate code can be a real nightmare.

2021-12-01 19:26 UTC, jgates108 approved these changes
Looks good, a couple of minor comments. It wont deadlock and all calls to stop() will wait until the thread has stopped. 

I like to be painfully obvious about the connections between condition variables, the underlying condition(s), and mutex.

2021-12-01 19:27 UTC, jgates108 commented on tests/test_Thread.cpp
> +            } catch (std::runtime_error&) {
True, but now they don't get to the test. Once _thread is nullptr, the test stops happening, so following calls to stop should not trip it.

2021-12-01 20:24 UTC, pkubanek commented on src/LSST/cRIO/Thread.cpp
> +Thread::Thread() : keepRunning(false), _threadStarted(false) { _thread = NULL; }
Thanks, wasn't too much aware of that C++11 feature. Changed as suggested.

2021-12-01 20:55 UTC, merged